apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sudoku

  template:
    metadata:
      labels:
        app: sudoku

    spec:
      containers:
      - name: sudoku-container
        image: varrinkalaprasad/sudoku-game:v1

        ports:
        - containerPort: 80
